KEY_COUNT_DOCUMENTS = "COUNT_TOTAL_DOCUMENTS"

KEY_TM_DICT = "TEMP_DICT_HASH"
KEY_HM_DICT = "MAIN_DICT_HASH"

KEY_TASK_ID = "TASK_ID"
KEY_TASK_QUEUE = "TASK_QUEUE"

KEY_RESPONSE_NUM_BREAK_IN_PROCESSING = "NUM_BREAK_IN_PROCESS"
KEY_RESPONSE_NUM_MERGE_IN_PROCESSING = "NUM_MERGE_IN_PROCESS"

KEY_RESPONSE_BREAK_FAIL_QUEUE = "RESPONSE_BREAK_FAIL_QUEUE"
KEY_RESPONSE_MERGE_FAIL_QUEUE = "RESPONSE_MERGE_FAIL_QUEUE"

KEY_RESPONSE_QUERY_HASH = "RESPONSE_QUERY_HASH"
